spring:
  datasource:
    url: jdbc:postgresql://customerservice.cqokpt4nuw0j.eu-central-1.rds.amazonaws.com/customer_service
    username: postgres
    password: customer-service
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    username: kovalchuk.roman03@gmail.com
    password: @aws.mail.password@
    port: 465
    protocol: smtps
    debug: true
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true

cloud:
  aws:
    credentials:
      access-key: @aws.s3.acces.key@
      secret-key: @aws.s3.secret.key@
    region:
      static: eu-central-1
    stack:
      auto: false

amazon:
  s3:
    bucket:
      name: 4vesla

jwt:
  secret: 4vesla

web:
  backend:
    host: "localhost:8080"
  frontend:
    host: "nashdomen.com"
