-- auto-generated definition
create table customer
(
    id              bigint generated by default as identity
        primary key,
    birth_date      date,
    name            varchar(255),
    phone_number    varchar(255),
    surname         varchar(255),
    activation_code varchar(255),
    email           varchar(255),
    password        varchar(255)
);

alter table customer
    owner to postgres;


-- auto-generated definition
create table user_role
(
    user_id bigint not null
        constraint fko1o9666pxemt8jqcp49gkfjew
            references customer,
    roles   varchar(255)
);

alter table user_role
    owner to postgres;

