-- auto-generated definition
CREATE TABLE CUSTOMER
(
    id              BIGINT PRIMARY KEY,
    birth_date      DATE,
    name            VARCHAR(255),
    phone_number    VARCHAR(255),
    surname         VARCHAR(255),
    activation_code VARCHAR(255),
    email           VARCHAR(255),
    password        VARCHAR(255)
);

alter table customer
    owner to postgres;


ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );

-- auto-generated definition
CREATE TABLE user_role
(
    user_id BIGINT NOT NULL CONSTRAINT role_user_fk
            REFERENCES customer,
    roles   VARCHAR(255)
);

ALTER TABLE user_role
    owner TO postgres;