ALTER TABLE customer ALTER COLUMN email SET NOT NULL;
ALTER TABLE customer ADD CONSTRAINT unique_email UNIQUE(email);

ALTER TABLE customer ALTER COLUMN password SET NOT NULL;
ALTER TABLE customer ALTER COLUMN name SET NOT NULL;
